name: Deploy AWS Lambda 

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs:
  deploy-lambda: 
    runs-on: ubuntu-latest # Sets or specifies the type of runner that the job will run on
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python # SEtsups Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.13' # Specify the Python version

      - name: Install dependencies # installs my package dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lamda/requirements.txt -t lambda/

      - name: Configure AWS credentials # sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to AWS Lambda #Zips the Lambda function and updates it in AWS
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
        